export const SUCCESS_MSG_POPUP = {
    SET_SUCCESS: 'SET_SUCCESS',
    HIDE_SUCCESS: 'HIDE_SUCCESS',
    SUCCESS_TOAST: 'SUCCESS_TOAST'
};

export const ERROR_ACTION_TYPES= {
    SET_ERROR:'SET_ERROR',
    HIDE_ERROR:'HIDE_ERROR'
}