export const MOVIES_DATA_LOADING = "MOVIES_DATA_LOADING";
export const MOVIES_DATA_SUCCESS = "MOVIES_DATA_SUCCESS";
export const MOVIES_DATA_ERROR = "MOVIES_DATA_ERROR";


export const LATESTMOVIES_DATA_LOADING = "LATESTMOVIES_DATA_LOADING";
export const LATESTMOVIES_DATA_SUCCESS = "LATESTMOVIES_DATA_SUCCESS";
export const LATESTMOVIES_DATA_ERROR = "LATESTMOVIES_DATA_ERROR";

export const UPCOMMING_MOVIES_DATA_LOADING = "UPCOMMING_MOVIES_DATA_LOADING";
export const UPCOMMING_MOVIES_DATA_SUCCESS = "UPCOMMING_MOVIES_DATA_SUCCESS";
export const UPCOMMING_MOVIES_DATA_ERROR = "UPCOMMING_MOVIES_DATA_ERROR";

export const WEB_SERIES_DATA_LOADING = "WEB_SERIES_DATA_LOADING";
export const WEB_SERIES_DATA_SUCCESS = "WEB_SERIES_DATA_SUCCESS";
export const WEB_SERIES_DATA_ERROR = "WEB_SERIES_DATA_ERROR";